#!/usr/bin/env python3

"""
Author:     Diego Maldonado (@dmnunez1993)
Maintainer: Emiliano Borghi (@eborghi10)
"""

import argparse
import docker_utils as ut
import os

def main():

    # Set image to compile
    image_name = 'ros_foxy'

    # Build selected image
    command = 'cd {} && make {}'.format(os.path.join(ut.get_repo_root(), 'docker'), image_name)
    ut.run_command(command)

if __name__ == '__main__':
    main()
